--- #YAML:1.0
name:                IO-Zlib
version:             1.07
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Compress::Zlib:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
